# Generated by Django 2.2.2 on 2019-06-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facturer_info',
            fields=[
                ('fac_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fac_name', models.CharField(max_length=15)),
                ('fac_position', models.CharField(max_length=30)),
                ('fac_phone_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Good_info',
            fields=[
                ('good_name', models.CharField(max_length=20)),
                ('good_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('in_price', models.IntegerField()),
                ('out_price', models.IntegerField()),
                ('fac_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shandian.facturer_info')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_info',
            fields=[
                ('shop_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('shop_position', models.CharField(max_length=30)),
                ('shop_phone_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('shop_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shandian.Shop_info')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_num', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('good_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shandian.Good_info')),
                ('shop_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shandian.Shop_info')),
            ],
        ),
        migrations.AddField(
            model_name='good_info',
            name='shop_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shandian.Shop_info'),
        ),
        migrations.AlterUniqueTogether(
            name='good_info',
            unique_together={('good_num', 'shop_num')},
        ),
    ]
