# Generated by Django 2.2.2 on 2019-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shandian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good_info',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
