# Generated by Django 2.2.2 on 2019-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shandian', '0002_auto_20190611_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good_info',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='good_info',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='good_info',
            name='in_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='good_info',
            name='out_price',
            field=models.IntegerField(null=True),
        ),
    ]
