# Generated by Django 2.2.2 on 2019-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shandian', '0003_auto_20190611_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_records',
            name='profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales_records',
            name='sales_num',
            field=models.IntegerField(null=True),
        ),
    ]
